-- -------------------------------------------------------------
-- 
-- File Name: hdlsrc\dspprogfirhdl\Discrete_FIR_Filter.vhd
-- Created: 2021-09-08 14:26:52
-- 
-- Generated by MATLAB 9.9 and HDL Coder 3.17
-- 
-- -------------------------------------------------------------


-- -------------------------------------------------------------
-- 
-- Module: Discrete_FIR_Filter
-- Source Path: dspprogfirhdl/Programmable FIR via Registers/Discrete FIR Filter
-- Hierarchy Level: 1
-- 
-- -------------------------------------------------------------
LIBRARY IEEE;
USE IEEE.std_logic_1164.ALL;
USE IEEE.numeric_std.ALL;
USE work.Programmable_FIR_via_Registers_pkg_adc.ALL;

ENTITY Discrete_FIR_Filter_adc IS
  PORT( clk                               :   IN    std_logic;
        reset                             :   IN    std_logic;
        enb                               :   IN    std_logic;
        Discrete_FIR_Filter_in            :   IN    std_logic_vector(13 DOWNTO 0);  -- sfix14_En13
        Discrete_FIR_Filter_coeff         :   IN    vector_of_std_logic_vector14(0 TO 6);  -- sfix14_En13 [7]
        Discrete_FIR_Filter_out           :   OUT   std_logic_vector(14 DOWNTO 0)  -- sfix15_En13
        );
END Discrete_FIR_Filter_adc;


ARCHITECTURE rtl OF Discrete_FIR_Filter_adc IS

  -- Signals
  SIGNAL Discrete_FIR_Filter_in_signed    : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL Discrete_FIR_Filter_coeff_0      : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL delay_pipeline_1                 : vector_of_signed14(0 TO 5);  -- sfix14_En13 [9]
  SIGNAL multiplier_mul_temp              : signed(27 DOWNTO 0);  -- sfix28_En26
  SIGNAL product1                         : signed(28 DOWNTO 0);  -- sfix29_En29
  SIGNAL delay_pipeline_0                 : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL Discrete_FIR_Filter_coeff_1      : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL multiplier_mul_temp_1            : signed(27 DOWNTO 0);  -- sfix28_En26
  SIGNAL product2                         : signed(28 DOWNTO 0);  -- sfix29_En29
  SIGNAL adder_add_cast                   : signed(30 DOWNTO 0);  -- sfix31_En29
  SIGNAL adder_add_cast_1                 : signed(30 DOWNTO 0);  -- sfix31_En29
  SIGNAL sum1                             : signed(30 DOWNTO 0);  -- sfix31_En29
  SIGNAL delay_pipeline_1_1               : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL Discrete_FIR_Filter_coeff_2      : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL multiplier_mul_temp_2            : signed(27 DOWNTO 0);  -- sfix28_En26
  SIGNAL product3                         : signed(28 DOWNTO 0);  -- sfix29_En29
  SIGNAL adder_add_cast_2                 : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL adder_add_cast_3                 : signed(30 DOWNTO 0);  -- sfix31_En29
  SIGNAL adder_add_cast_4                 : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL adder_add_temp                   : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL sum2                             : signed(30 DOWNTO 0);  -- sfix31_En29
  SIGNAL delay_pipeline_2                 : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL Discrete_FIR_Filter_coeff_3      : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL multiplier_mul_temp_3            : signed(27 DOWNTO 0);  -- sfix28_En26
  SIGNAL product4                         : signed(28 DOWNTO 0);  -- sfix29_En29
  SIGNAL adder_add_cast_5                 : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL adder_add_cast_6                 : signed(30 DOWNTO 0);  -- sfix31_En29
  SIGNAL adder_add_cast_7                 : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL adder_add_temp_1                 : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL sum3                             : signed(30 DOWNTO 0);  -- sfix31_En29
  SIGNAL delay_pipeline_3                 : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL Discrete_FIR_Filter_coeff_4      : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL multiplier_mul_temp_4            : signed(27 DOWNTO 0);  -- sfix28_En26
  SIGNAL product5                         : signed(28 DOWNTO 0);  -- sfix29_En29
  SIGNAL adder_add_cast_8                 : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL adder_add_cast_9                 : signed(30 DOWNTO 0);  -- sfix31_En29
  SIGNAL adder_add_cast_10                : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL adder_add_temp_2                 : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL sum4                             : signed(30 DOWNTO 0);  -- sfix31_En29
  SIGNAL delay_pipeline_4                 : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL Discrete_FIR_Filter_coeff_5      : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL multiplier_mul_temp_5            : signed(27 DOWNTO 0);  -- sfix28_En26
  SIGNAL product6                         : signed(28 DOWNTO 0);  -- sfix29_En29
  SIGNAL adder_add_cast_11                : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL adder_add_cast_12                : signed(30 DOWNTO 0);  -- sfix31_En29
  SIGNAL adder_add_cast_13                : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL adder_add_temp_3                 : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL sum5                             : signed(30 DOWNTO 0);  -- sfix31_En29
  SIGNAL delay_pipeline_5                 : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL Discrete_FIR_Filter_coeff_6      : signed(13 DOWNTO 0);  -- sfix14_En13
  SIGNAL multiplier_mul_temp_6            : signed(27 DOWNTO 0);  -- sfix28_En26
  SIGNAL product7                         : signed(28 DOWNTO 0);  -- sfix29_En29
  SIGNAL adder_add_cast_14                : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL adder_add_cast_15                : signed(30 DOWNTO 0);  -- sfix31_En29
  SIGNAL adder_add_cast_16                : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL adder_add_temp_4                 : signed(31 DOWNTO 0);  -- sfix32_En29
  SIGNAL sum6                             : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_6                 : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_7      : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_7            : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product8                         : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_17                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_18                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_19                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_5                 : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum7                             : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_7                 : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_8      : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_8            : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product9                         : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_20                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_21                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_22                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_6                 : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum8                             : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_8                 : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_9      : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_9            : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product10                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_23                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_24                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_25                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_7                 : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum9                             : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_9                 : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_10     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_10           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product11                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_26                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_27                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_28                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_8                 : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum10                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_10                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_11     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_11           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product12                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_29                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_30                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_31                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_9                 : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum11                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_11                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_12     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_12           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product13                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_32                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_33                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_34                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_10                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum12                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_12                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_13     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_13           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product14                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_35                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_36                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_37                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_11                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum13                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_13                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_14     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_14           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product15                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_38                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_39                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_40                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_12                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum14                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_14                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_15     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_15           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product16                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_41                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_42                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_43                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_13                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum15                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_15                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_16     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_16           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product17                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_44                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_45                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_46                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_14                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum16                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_16                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_17     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_17           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product18                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_47                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_48                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_49                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_15                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum17                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_17                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_18     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_18           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product19                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_50                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_51                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_52                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_16                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum18                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_18                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_19     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_19           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product20                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_53                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_54                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_55                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_17                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum19                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_19                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_20     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_20           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product21                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_56                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_57                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_58                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_18                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum20                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_20                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_21     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_21           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product22                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_59                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_60                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_61                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_19                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum21                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_21                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_22     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_22           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product23                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_62                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_63                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_64                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_20                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum22                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_22                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_23     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_23           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product24                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_65                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_66                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_67                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_21                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum23                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_23                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_24     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_24           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product25                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_68                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_69                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_70                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_22                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum24                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_24                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_25     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_25           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product26                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_71                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_72                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_73                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_23                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum25                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_25                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_26     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_26           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product27                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_74                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_75                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_76                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_24                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum26                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_26                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_27     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_27           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product28                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_77                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_78                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_79                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_25                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum27                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_27                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_28     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_28           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product29                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_80                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_81                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_82                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_26                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum28                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_28                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_29     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_29           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product30                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_83                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_84                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_85                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_27                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum29                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_29                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_30     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_30           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product31                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_86                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_87                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_88                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_28                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum30                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_30                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_31     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_31           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product32                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_89                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_90                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_91                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_29                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum31                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_31                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_32     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_32           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product33                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_92                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_93                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_94                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_30                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum32                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_32                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_33     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_33           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product34                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_95                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_96                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_97                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_31                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum33                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_33                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_34     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_34           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product35                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_98                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_99                : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_100               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_32                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum34                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_34                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_35     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_35           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product36                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_101               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_102               : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_103               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_33                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum35                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_35                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_36     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_36           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product37                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_104               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_105               : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_106               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_34                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum36                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_36                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_37     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_37           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product38                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_107               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_108               : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_109               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_35                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum37                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_37                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_38     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_38           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product39                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_110               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_111               : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_112               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_36                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum38                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_38                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_39     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_39           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product40                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_113               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_114               : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_115               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_37                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum39                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_39                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_40     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_40           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product41                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_116               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_117               : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_118               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_38                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum40                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_40                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_41     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_41           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product42                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_119               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_120               : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_121               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_39                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum41                            : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL delay_pipeline_41                : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL Discrete_FIR_Filter_coeff_42     : signed(13 DOWNTO 0);  -- sfix14_En13
--  SIGNAL multiplier_mul_temp_42           : signed(27 DOWNTO 0);  -- sfix28_En26
--  SIGNAL product43                        : signed(28 DOWNTO 0);  -- sfix29_En29
--  SIGNAL adder_add_cast_122               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_cast_123               : signed(30 DOWNTO 0);  -- sfix31_En29
--  SIGNAL adder_add_cast_124               : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL adder_add_temp_40                : signed(31 DOWNTO 0);  -- sfix32_En29
--  SIGNAL sum42                            : signed(30 DOWNTO 0);  -- sfix31_En29
  SIGNAL output_typeconvert               : signed(14 DOWNTO 0);  -- sfix15_En13

BEGIN
  Discrete_FIR_Filter_in_signed <= signed(Discrete_FIR_Filter_in);

  Discrete_FIR_Filter_coeff_0 <= signed(Discrete_FIR_Filter_coeff(0));

  Delay_Pipeline_process : PROCESS (clk, reset)
  BEGIN
    IF reset = '1' THEN
      delay_pipeline_1 <= (OTHERS => to_signed(16#0000#, 14));
    ELSIF clk'EVENT AND clk = '1' THEN
      IF enb = '1' THEN
        delay_pipeline_1(0) <= Discrete_FIR_Filter_in_signed;
        delay_pipeline_1(1 TO 5) <= delay_pipeline_1(0 TO 4);
      END IF;
    END IF;
  END PROCESS Delay_Pipeline_process;


  multiplier_mul_temp <= Discrete_FIR_Filter_in_signed * Discrete_FIR_Filter_coeff_0;
  
  product1 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp(27) = '0') AND (multiplier_mul_temp(26 DOWNTO 25) /= "00") ELSE
      "10000000000000000000000000000" WHEN (multiplier_mul_temp(27) = '1') AND (multiplier_mul_temp(26 DOWNTO 25) /= "11") ELSE
      multiplier_mul_temp(25 DOWNTO 0) & '0' & '0' & '0';

  delay_pipeline_0 <= delay_pipeline_1(0);

  Discrete_FIR_Filter_coeff_1 <= signed(Discrete_FIR_Filter_coeff(1));

  multiplier_mul_temp_1 <= delay_pipeline_0 * Discrete_FIR_Filter_coeff_1;
  
  product2 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_1(27) = '0') AND (multiplier_mul_temp_1(26 DOWNTO 25) /= "00") ELSE
      "10000000000000000000000000000" WHEN (multiplier_mul_temp_1(27) = '1') AND (multiplier_mul_temp_1(26 DOWNTO 25) /= "11") ELSE
      multiplier_mul_temp_1(25 DOWNTO 0) & '0' & '0' & '0';

  adder_add_cast <= resize(product1, 31);
  adder_add_cast_1 <= resize(product2, 31);
  sum1 <= adder_add_cast + adder_add_cast_1;

  delay_pipeline_1_1 <= delay_pipeline_1(1);

  Discrete_FIR_Filter_coeff_2 <= signed(Discrete_FIR_Filter_coeff(2));

  multiplier_mul_temp_2 <= delay_pipeline_1_1 * Discrete_FIR_Filter_coeff_2;
  
  product3 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_2(27) = '0') AND (multiplier_mul_temp_2(26 DOWNTO 25) /= "00") ELSE
      "10000000000000000000000000000" WHEN (multiplier_mul_temp_2(27) = '1') AND (multiplier_mul_temp_2(26 DOWNTO 25) /= "11") ELSE
      multiplier_mul_temp_2(25 DOWNTO 0) & '0' & '0' & '0';

  adder_add_cast_2 <= resize(sum1, 32);
  adder_add_cast_3 <= resize(product3, 31);
  adder_add_cast_4 <= resize(adder_add_cast_3, 32);
  adder_add_temp <= adder_add_cast_2 + adder_add_cast_4;
  
  sum2 <= "0111111111111111111111111111111" WHEN (adder_add_temp(31) = '0') AND (adder_add_temp(30) /= '0') ELSE
      "1000000000000000000000000000000" WHEN (adder_add_temp(31) = '1') AND (adder_add_temp(30) /= '1') ELSE
      adder_add_temp(30 DOWNTO 0);

  delay_pipeline_2 <= delay_pipeline_1(2);

  Discrete_FIR_Filter_coeff_3 <= signed(Discrete_FIR_Filter_coeff(3));

  multiplier_mul_temp_3 <= delay_pipeline_2 * Discrete_FIR_Filter_coeff_3;
  
  product4 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_3(27) = '0') AND (multiplier_mul_temp_3(26 DOWNTO 25) /= "00") ELSE
      "10000000000000000000000000000" WHEN (multiplier_mul_temp_3(27) = '1') AND (multiplier_mul_temp_3(26 DOWNTO 25) /= "11") ELSE
      multiplier_mul_temp_3(25 DOWNTO 0) & '0' & '0' & '0';

  adder_add_cast_5 <= resize(sum2, 32);
  adder_add_cast_6 <= resize(product4, 31);
  adder_add_cast_7 <= resize(adder_add_cast_6, 32);
  adder_add_temp_1 <= adder_add_cast_5 + adder_add_cast_7;
  
  sum3 <= "0111111111111111111111111111111" WHEN (adder_add_temp_1(31) = '0') AND (adder_add_temp_1(30) /= '0') ELSE
      "1000000000000000000000000000000" WHEN (adder_add_temp_1(31) = '1') AND (adder_add_temp_1(30) /= '1') ELSE
      adder_add_temp_1(30 DOWNTO 0);

  delay_pipeline_3 <= delay_pipeline_1(3);

  Discrete_FIR_Filter_coeff_4 <= signed(Discrete_FIR_Filter_coeff(4));

  multiplier_mul_temp_4 <= delay_pipeline_3 * Discrete_FIR_Filter_coeff_4;
  
  product5 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_4(27) = '0') AND (multiplier_mul_temp_4(26 DOWNTO 25) /= "00") ELSE
      "10000000000000000000000000000" WHEN (multiplier_mul_temp_4(27) = '1') AND (multiplier_mul_temp_4(26 DOWNTO 25) /= "11") ELSE
      multiplier_mul_temp_4(25 DOWNTO 0) & '0' & '0' & '0';

  adder_add_cast_8 <= resize(sum3, 32);
  adder_add_cast_9 <= resize(product5, 31);
  adder_add_cast_10 <= resize(adder_add_cast_9, 32);
  adder_add_temp_2 <= adder_add_cast_8 + adder_add_cast_10;
  
  sum4 <= "0111111111111111111111111111111" WHEN (adder_add_temp_2(31) = '0') AND (adder_add_temp_2(30) /= '0') ELSE
      "1000000000000000000000000000000" WHEN (adder_add_temp_2(31) = '1') AND (adder_add_temp_2(30) /= '1') ELSE
      adder_add_temp_2(30 DOWNTO 0);

  delay_pipeline_4 <= delay_pipeline_1(4);

  Discrete_FIR_Filter_coeff_5 <= signed(Discrete_FIR_Filter_coeff(5));

  multiplier_mul_temp_5 <= delay_pipeline_4 * Discrete_FIR_Filter_coeff_5;
  
  product6 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_5(27) = '0') AND (multiplier_mul_temp_5(26 DOWNTO 25) /= "00") ELSE
      "10000000000000000000000000000" WHEN (multiplier_mul_temp_5(27) = '1') AND (multiplier_mul_temp_5(26 DOWNTO 25) /= "11") ELSE
      multiplier_mul_temp_5(25 DOWNTO 0) & '0' & '0' & '0';

  adder_add_cast_11 <= resize(sum4, 32);
  adder_add_cast_12 <= resize(product6, 31);
  adder_add_cast_13 <= resize(adder_add_cast_12, 32);
  adder_add_temp_3 <= adder_add_cast_11 + adder_add_cast_13;
  
  sum5 <= "0111111111111111111111111111111" WHEN (adder_add_temp_3(31) = '0') AND (adder_add_temp_3(30) /= '0') ELSE
      "1000000000000000000000000000000" WHEN (adder_add_temp_3(31) = '1') AND (adder_add_temp_3(30) /= '1') ELSE
      adder_add_temp_3(30 DOWNTO 0);

  delay_pipeline_5 <= delay_pipeline_1(5);

  Discrete_FIR_Filter_coeff_6 <= signed(Discrete_FIR_Filter_coeff(6));

  multiplier_mul_temp_6 <= delay_pipeline_5 * Discrete_FIR_Filter_coeff_6;
  
  product7 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_6(27) = '0') AND (multiplier_mul_temp_6(26 DOWNTO 25) /= "00") ELSE
      "10000000000000000000000000000" WHEN (multiplier_mul_temp_6(27) = '1') AND (multiplier_mul_temp_6(26 DOWNTO 25) /= "11") ELSE
      multiplier_mul_temp_6(25 DOWNTO 0) & '0' & '0' & '0';

  adder_add_cast_14 <= resize(sum5, 32);
  adder_add_cast_15 <= resize(product7, 31);
  adder_add_cast_16 <= resize(adder_add_cast_15, 32);
  adder_add_temp_4 <= adder_add_cast_14 + adder_add_cast_16;
  
  sum6 <= "0111111111111111111111111111111" WHEN (adder_add_temp_4(31) = '0') AND (adder_add_temp_4(30) /= '0') ELSE
      "1000000000000000000000000000000" WHEN (adder_add_temp_4(31) = '1') AND (adder_add_temp_4(30) /= '1') ELSE
      adder_add_temp_4(30 DOWNTO 0);

--  delay_pipeline_6 <= delay_pipeline_1(6);
--
--  Discrete_FIR_Filter_coeff_7 <= signed(Discrete_FIR_Filter_coeff(7));
--
--  multiplier_mul_temp_7 <= delay_pipeline_6 * Discrete_FIR_Filter_coeff_7;
--  
--  product8 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_7(27) = '0') AND (multiplier_mul_temp_7(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_7(27) = '1') AND (multiplier_mul_temp_7(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_7(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_17 <= resize(sum6, 32);
--  adder_add_cast_18 <= resize(product8, 31);
--  adder_add_cast_19 <= resize(adder_add_cast_18, 32);
--  adder_add_temp_5 <= adder_add_cast_17 + adder_add_cast_19;
--  
--  sum7 <= "0111111111111111111111111111111" WHEN (adder_add_temp_5(31) = '0') AND (adder_add_temp_5(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_5(31) = '1') AND (adder_add_temp_5(30) /= '1') ELSE
--      adder_add_temp_5(30 DOWNTO 0);

--  delay_pipeline_7 <= delay_pipeline_1(7);
--
--  Discrete_FIR_Filter_coeff_8 <= signed(Discrete_FIR_Filter_coeff(8));
--
--  multiplier_mul_temp_8 <= delay_pipeline_7 * Discrete_FIR_Filter_coeff_8;
--  
--  product9 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_8(27) = '0') AND (multiplier_mul_temp_8(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_8(27) = '1') AND (multiplier_mul_temp_8(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_8(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_20 <= resize(sum7, 32);
--  adder_add_cast_21 <= resize(product9, 31);
--  adder_add_cast_22 <= resize(adder_add_cast_21, 32);
--  adder_add_temp_6 <= adder_add_cast_20 + adder_add_cast_22;
--  
--  sum8 <= "0111111111111111111111111111111" WHEN (adder_add_temp_6(31) = '0') AND (adder_add_temp_6(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_6(31) = '1') AND (adder_add_temp_6(30) /= '1') ELSE
--      adder_add_temp_6(30 DOWNTO 0);
--
--  delay_pipeline_8 <= delay_pipeline_1(8);
--
--  Discrete_FIR_Filter_coeff_9 <= signed(Discrete_FIR_Filter_coeff(9));
--
--  multiplier_mul_temp_9 <= delay_pipeline_8 * Discrete_FIR_Filter_coeff_9;
--  
--  product10 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_9(27) = '0') AND (multiplier_mul_temp_9(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_9(27) = '1') AND (multiplier_mul_temp_9(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_9(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_23 <= resize(sum8, 32);
--  adder_add_cast_24 <= resize(product10, 31);
--  adder_add_cast_25 <= resize(adder_add_cast_24, 32);
--  adder_add_temp_7 <= adder_add_cast_23 + adder_add_cast_25;
--  
--  sum9 <= "0111111111111111111111111111111" WHEN (adder_add_temp_7(31) = '0') AND (adder_add_temp_7(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_7(31) = '1') AND (adder_add_temp_7(30) /= '1') ELSE
--      adder_add_temp_7(30 DOWNTO 0);
--
--  delay_pipeline_9 <= delay_pipeline_1(9);
--
--  Discrete_FIR_Filter_coeff_10 <= signed(Discrete_FIR_Filter_coeff(10));
--
--  multiplier_mul_temp_10 <= delay_pipeline_9 * Discrete_FIR_Filter_coeff_10;
--  
--  product11 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_10(27) = '0') AND (multiplier_mul_temp_10(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_10(27) = '1') AND (multiplier_mul_temp_10(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_10(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_26 <= resize(sum9, 32);
--  adder_add_cast_27 <= resize(product11, 31);
--  adder_add_cast_28 <= resize(adder_add_cast_27, 32);
--  adder_add_temp_8 <= adder_add_cast_26 + adder_add_cast_28;
--  
--  sum10 <= "0111111111111111111111111111111" WHEN (adder_add_temp_8(31) = '0') AND (adder_add_temp_8(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_8(31) = '1') AND (adder_add_temp_8(30) /= '1') ELSE
--      adder_add_temp_8(30 DOWNTO 0);
--
--  delay_pipeline_10 <= delay_pipeline_1(10);
--
--  Discrete_FIR_Filter_coeff_11 <= signed(Discrete_FIR_Filter_coeff(11));
--
--  multiplier_mul_temp_11 <= delay_pipeline_10 * Discrete_FIR_Filter_coeff_11;
--  
--  product12 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_11(27) = '0') AND (multiplier_mul_temp_11(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_11(27) = '1') AND (multiplier_mul_temp_11(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_11(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_29 <= resize(sum10, 32);
--  adder_add_cast_30 <= resize(product12, 31);
--  adder_add_cast_31 <= resize(adder_add_cast_30, 32);
--  adder_add_temp_9 <= adder_add_cast_29 + adder_add_cast_31;
--  
--  sum11 <= "0111111111111111111111111111111" WHEN (adder_add_temp_9(31) = '0') AND (adder_add_temp_9(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_9(31) = '1') AND (adder_add_temp_9(30) /= '1') ELSE
--      adder_add_temp_9(30 DOWNTO 0);
--
--  delay_pipeline_11 <= delay_pipeline_1(11);
--
--  Discrete_FIR_Filter_coeff_12 <= signed(Discrete_FIR_Filter_coeff(12));
--
--  multiplier_mul_temp_12 <= delay_pipeline_11 * Discrete_FIR_Filter_coeff_12;
--  
--  product13 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_12(27) = '0') AND (multiplier_mul_temp_12(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_12(27) = '1') AND (multiplier_mul_temp_12(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_12(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_32 <= resize(sum11, 32);
--  adder_add_cast_33 <= resize(product13, 31);
--  adder_add_cast_34 <= resize(adder_add_cast_33, 32);
--  adder_add_temp_10 <= adder_add_cast_32 + adder_add_cast_34;
--  
--  sum12 <= "0111111111111111111111111111111" WHEN (adder_add_temp_10(31) = '0') AND (adder_add_temp_10(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_10(31) = '1') AND (adder_add_temp_10(30) /= '1') ELSE
--      adder_add_temp_10(30 DOWNTO 0);
--
--  delay_pipeline_12 <= delay_pipeline_1(12);
--
--  Discrete_FIR_Filter_coeff_13 <= signed(Discrete_FIR_Filter_coeff(13));
--
--  multiplier_mul_temp_13 <= delay_pipeline_12 * Discrete_FIR_Filter_coeff_13;
--  
--  product14 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_13(27) = '0') AND (multiplier_mul_temp_13(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_13(27) = '1') AND (multiplier_mul_temp_13(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_13(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_35 <= resize(sum12, 32);
--  adder_add_cast_36 <= resize(product14, 31);
--  adder_add_cast_37 <= resize(adder_add_cast_36, 32);
--  adder_add_temp_11 <= adder_add_cast_35 + adder_add_cast_37;
--  
--  sum13 <= "0111111111111111111111111111111" WHEN (adder_add_temp_11(31) = '0') AND (adder_add_temp_11(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_11(31) = '1') AND (adder_add_temp_11(30) /= '1') ELSE
--      adder_add_temp_11(30 DOWNTO 0);
--
--  delay_pipeline_13 <= delay_pipeline_1(13);
--
--  Discrete_FIR_Filter_coeff_14 <= signed(Discrete_FIR_Filter_coeff(14));
--
--  multiplier_mul_temp_14 <= delay_pipeline_13 * Discrete_FIR_Filter_coeff_14;
--  
--  product15 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_14(27) = '0') AND (multiplier_mul_temp_14(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_14(27) = '1') AND (multiplier_mul_temp_14(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_14(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_38 <= resize(sum13, 32);
--  adder_add_cast_39 <= resize(product15, 31);
--  adder_add_cast_40 <= resize(adder_add_cast_39, 32);
--  adder_add_temp_12 <= adder_add_cast_38 + adder_add_cast_40;
--  
--  sum14 <= "0111111111111111111111111111111" WHEN (adder_add_temp_12(31) = '0') AND (adder_add_temp_12(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_12(31) = '1') AND (adder_add_temp_12(30) /= '1') ELSE
--      adder_add_temp_12(30 DOWNTO 0);
--
--  delay_pipeline_14 <= delay_pipeline_1(14);
--
--  Discrete_FIR_Filter_coeff_15 <= signed(Discrete_FIR_Filter_coeff(15));
--
--  multiplier_mul_temp_15 <= delay_pipeline_14 * Discrete_FIR_Filter_coeff_15;
--  
--  product16 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_15(27) = '0') AND (multiplier_mul_temp_15(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_15(27) = '1') AND (multiplier_mul_temp_15(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_15(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_41 <= resize(sum14, 32);
--  adder_add_cast_42 <= resize(product16, 31);
--  adder_add_cast_43 <= resize(adder_add_cast_42, 32);
--  adder_add_temp_13 <= adder_add_cast_41 + adder_add_cast_43;
--  
--  sum15 <= "0111111111111111111111111111111" WHEN (adder_add_temp_13(31) = '0') AND (adder_add_temp_13(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_13(31) = '1') AND (adder_add_temp_13(30) /= '1') ELSE
--      adder_add_temp_13(30 DOWNTO 0);
--
--  delay_pipeline_15 <= delay_pipeline_1(15);
--
--  Discrete_FIR_Filter_coeff_16 <= signed(Discrete_FIR_Filter_coeff(16));
--
--  multiplier_mul_temp_16 <= delay_pipeline_15 * Discrete_FIR_Filter_coeff_16;
--  
--  product17 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_16(27) = '0') AND (multiplier_mul_temp_16(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_16(27) = '1') AND (multiplier_mul_temp_16(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_16(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_44 <= resize(sum15, 32);
--  adder_add_cast_45 <= resize(product17, 31);
--  adder_add_cast_46 <= resize(adder_add_cast_45, 32);
--  adder_add_temp_14 <= adder_add_cast_44 + adder_add_cast_46;
--  
--  sum16 <= "0111111111111111111111111111111" WHEN (adder_add_temp_14(31) = '0') AND (adder_add_temp_14(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_14(31) = '1') AND (adder_add_temp_14(30) /= '1') ELSE
--      adder_add_temp_14(30 DOWNTO 0);
--
--  delay_pipeline_16 <= delay_pipeline_1(16);
--
--  Discrete_FIR_Filter_coeff_17 <= signed(Discrete_FIR_Filter_coeff(17));
--
--  multiplier_mul_temp_17 <= delay_pipeline_16 * Discrete_FIR_Filter_coeff_17;
--  
--  product18 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_17(27) = '0') AND (multiplier_mul_temp_17(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_17(27) = '1') AND (multiplier_mul_temp_17(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_17(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_47 <= resize(sum16, 32);
--  adder_add_cast_48 <= resize(product18, 31);
--  adder_add_cast_49 <= resize(adder_add_cast_48, 32);
--  adder_add_temp_15 <= adder_add_cast_47 + adder_add_cast_49;
--  
--  sum17 <= "0111111111111111111111111111111" WHEN (adder_add_temp_15(31) = '0') AND (adder_add_temp_15(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_15(31) = '1') AND (adder_add_temp_15(30) /= '1') ELSE
--      adder_add_temp_15(30 DOWNTO 0);
--
--  delay_pipeline_17 <= delay_pipeline_1(17);
--
--  Discrete_FIR_Filter_coeff_18 <= signed(Discrete_FIR_Filter_coeff(18));
--
--  multiplier_mul_temp_18 <= delay_pipeline_17 * Discrete_FIR_Filter_coeff_18;
--  
--  product19 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_18(27) = '0') AND (multiplier_mul_temp_18(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_18(27) = '1') AND (multiplier_mul_temp_18(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_18(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_50 <= resize(sum17, 32);
--  adder_add_cast_51 <= resize(product19, 31);
--  adder_add_cast_52 <= resize(adder_add_cast_51, 32);
--  adder_add_temp_16 <= adder_add_cast_50 + adder_add_cast_52;
--  
--  sum18 <= "0111111111111111111111111111111" WHEN (adder_add_temp_16(31) = '0') AND (adder_add_temp_16(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_16(31) = '1') AND (adder_add_temp_16(30) /= '1') ELSE
--      adder_add_temp_16(30 DOWNTO 0);
--
--  delay_pipeline_18 <= delay_pipeline_1(18);
--
--  Discrete_FIR_Filter_coeff_19 <= signed(Discrete_FIR_Filter_coeff(19));
--
--  multiplier_mul_temp_19 <= delay_pipeline_18 * Discrete_FIR_Filter_coeff_19;
--  
--  product20 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_19(27) = '0') AND (multiplier_mul_temp_19(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_19(27) = '1') AND (multiplier_mul_temp_19(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_19(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_53 <= resize(sum18, 32);
--  adder_add_cast_54 <= resize(product20, 31);
--  adder_add_cast_55 <= resize(adder_add_cast_54, 32);
--  adder_add_temp_17 <= adder_add_cast_53 + adder_add_cast_55;
--  
--  sum19 <= "0111111111111111111111111111111" WHEN (adder_add_temp_17(31) = '0') AND (adder_add_temp_17(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_17(31) = '1') AND (adder_add_temp_17(30) /= '1') ELSE
--      adder_add_temp_17(30 DOWNTO 0);
--
--  delay_pipeline_19 <= delay_pipeline_1(19);
--
--  Discrete_FIR_Filter_coeff_20 <= signed(Discrete_FIR_Filter_coeff(20));
--
--  multiplier_mul_temp_20 <= delay_pipeline_19 * Discrete_FIR_Filter_coeff_20;
--  
--  product21 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_20(27) = '0') AND (multiplier_mul_temp_20(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_20(27) = '1') AND (multiplier_mul_temp_20(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_20(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_56 <= resize(sum19, 32);
--  adder_add_cast_57 <= resize(product21, 31);
--  adder_add_cast_58 <= resize(adder_add_cast_57, 32);
--  adder_add_temp_18 <= adder_add_cast_56 + adder_add_cast_58;
--  
--  sum20 <= "0111111111111111111111111111111" WHEN (adder_add_temp_18(31) = '0') AND (adder_add_temp_18(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_18(31) = '1') AND (adder_add_temp_18(30) /= '1') ELSE
--      adder_add_temp_18(30 DOWNTO 0);
--
--  delay_pipeline_20 <= delay_pipeline_1(20);
--
--  Discrete_FIR_Filter_coeff_21 <= signed(Discrete_FIR_Filter_coeff(21));
--
--  multiplier_mul_temp_21 <= delay_pipeline_20 * Discrete_FIR_Filter_coeff_21;
--  
--  product22 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_21(27) = '0') AND (multiplier_mul_temp_21(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_21(27) = '1') AND (multiplier_mul_temp_21(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_21(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_59 <= resize(sum20, 32);
--  adder_add_cast_60 <= resize(product22, 31);
--  adder_add_cast_61 <= resize(adder_add_cast_60, 32);
--  adder_add_temp_19 <= adder_add_cast_59 + adder_add_cast_61;
--  
--  sum21 <= "0111111111111111111111111111111" WHEN (adder_add_temp_19(31) = '0') AND (adder_add_temp_19(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_19(31) = '1') AND (adder_add_temp_19(30) /= '1') ELSE
--      adder_add_temp_19(30 DOWNTO 0);
--
--  delay_pipeline_21 <= delay_pipeline_1(21);
--
--  Discrete_FIR_Filter_coeff_22 <= signed(Discrete_FIR_Filter_coeff(22));
--
--  multiplier_mul_temp_22 <= delay_pipeline_21 * Discrete_FIR_Filter_coeff_22;
--  
--  product23 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_22(27) = '0') AND (multiplier_mul_temp_22(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_22(27) = '1') AND (multiplier_mul_temp_22(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_22(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_62 <= resize(sum21, 32);
--  adder_add_cast_63 <= resize(product23, 31);
--  adder_add_cast_64 <= resize(adder_add_cast_63, 32);
--  adder_add_temp_20 <= adder_add_cast_62 + adder_add_cast_64;
--  
--  sum22 <= "0111111111111111111111111111111" WHEN (adder_add_temp_20(31) = '0') AND (adder_add_temp_20(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_20(31) = '1') AND (adder_add_temp_20(30) /= '1') ELSE
--      adder_add_temp_20(30 DOWNTO 0);
--
--  delay_pipeline_22 <= delay_pipeline_1(22);
--
--  Discrete_FIR_Filter_coeff_23 <= signed(Discrete_FIR_Filter_coeff(23));
--
--  multiplier_mul_temp_23 <= delay_pipeline_22 * Discrete_FIR_Filter_coeff_23;
--  
--  product24 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_23(27) = '0') AND (multiplier_mul_temp_23(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_23(27) = '1') AND (multiplier_mul_temp_23(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_23(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_65 <= resize(sum22, 32);
--  adder_add_cast_66 <= resize(product24, 31);
--  adder_add_cast_67 <= resize(adder_add_cast_66, 32);
--  adder_add_temp_21 <= adder_add_cast_65 + adder_add_cast_67;
--  
--  sum23 <= "0111111111111111111111111111111" WHEN (adder_add_temp_21(31) = '0') AND (adder_add_temp_21(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_21(31) = '1') AND (adder_add_temp_21(30) /= '1') ELSE
--      adder_add_temp_21(30 DOWNTO 0);
--
--  delay_pipeline_23 <= delay_pipeline_1(23);
--
--  Discrete_FIR_Filter_coeff_24 <= signed(Discrete_FIR_Filter_coeff(24));
--
--  multiplier_mul_temp_24 <= delay_pipeline_23 * Discrete_FIR_Filter_coeff_24;
--  
--  product25 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_24(27) = '0') AND (multiplier_mul_temp_24(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_24(27) = '1') AND (multiplier_mul_temp_24(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_24(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_68 <= resize(sum23, 32);
--  adder_add_cast_69 <= resize(product25, 31);
--  adder_add_cast_70 <= resize(adder_add_cast_69, 32);
--  adder_add_temp_22 <= adder_add_cast_68 + adder_add_cast_70;
--  
--  sum24 <= "0111111111111111111111111111111" WHEN (adder_add_temp_22(31) = '0') AND (adder_add_temp_22(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_22(31) = '1') AND (adder_add_temp_22(30) /= '1') ELSE
--      adder_add_temp_22(30 DOWNTO 0);
--
--  delay_pipeline_24 <= delay_pipeline_1(24);
--
--  Discrete_FIR_Filter_coeff_25 <= signed(Discrete_FIR_Filter_coeff(25));
--
--  multiplier_mul_temp_25 <= delay_pipeline_24 * Discrete_FIR_Filter_coeff_25;
--  
--  product26 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_25(27) = '0') AND (multiplier_mul_temp_25(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_25(27) = '1') AND (multiplier_mul_temp_25(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_25(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_71 <= resize(sum24, 32);
--  adder_add_cast_72 <= resize(product26, 31);
--  adder_add_cast_73 <= resize(adder_add_cast_72, 32);
--  adder_add_temp_23 <= adder_add_cast_71 + adder_add_cast_73;
--  
--  sum25 <= "0111111111111111111111111111111" WHEN (adder_add_temp_23(31) = '0') AND (adder_add_temp_23(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_23(31) = '1') AND (adder_add_temp_23(30) /= '1') ELSE
--      adder_add_temp_23(30 DOWNTO 0);
--
--  delay_pipeline_25 <= delay_pipeline_1(25);
--
--  Discrete_FIR_Filter_coeff_26 <= signed(Discrete_FIR_Filter_coeff(26));
--
--  multiplier_mul_temp_26 <= delay_pipeline_25 * Discrete_FIR_Filter_coeff_26;
--  
--  product27 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_26(27) = '0') AND (multiplier_mul_temp_26(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_26(27) = '1') AND (multiplier_mul_temp_26(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_26(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_74 <= resize(sum25, 32);
--  adder_add_cast_75 <= resize(product27, 31);
--  adder_add_cast_76 <= resize(adder_add_cast_75, 32);
--  adder_add_temp_24 <= adder_add_cast_74 + adder_add_cast_76;
--  
--  sum26 <= "0111111111111111111111111111111" WHEN (adder_add_temp_24(31) = '0') AND (adder_add_temp_24(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_24(31) = '1') AND (adder_add_temp_24(30) /= '1') ELSE
--      adder_add_temp_24(30 DOWNTO 0);
--
--  delay_pipeline_26 <= delay_pipeline_1(26);
--
--  Discrete_FIR_Filter_coeff_27 <= signed(Discrete_FIR_Filter_coeff(27));
--
--  multiplier_mul_temp_27 <= delay_pipeline_26 * Discrete_FIR_Filter_coeff_27;
--  
--  product28 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_27(27) = '0') AND (multiplier_mul_temp_27(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_27(27) = '1') AND (multiplier_mul_temp_27(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_27(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_77 <= resize(sum26, 32);
--  adder_add_cast_78 <= resize(product28, 31);
--  adder_add_cast_79 <= resize(adder_add_cast_78, 32);
--  adder_add_temp_25 <= adder_add_cast_77 + adder_add_cast_79;
--  
--  sum27 <= "0111111111111111111111111111111" WHEN (adder_add_temp_25(31) = '0') AND (adder_add_temp_25(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_25(31) = '1') AND (adder_add_temp_25(30) /= '1') ELSE
--      adder_add_temp_25(30 DOWNTO 0);
--
--  delay_pipeline_27 <= delay_pipeline_1(27);
--
--  Discrete_FIR_Filter_coeff_28 <= signed(Discrete_FIR_Filter_coeff(28));
--
--  multiplier_mul_temp_28 <= delay_pipeline_27 * Discrete_FIR_Filter_coeff_28;
--  
--  product29 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_28(27) = '0') AND (multiplier_mul_temp_28(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_28(27) = '1') AND (multiplier_mul_temp_28(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_28(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_80 <= resize(sum27, 32);
--  adder_add_cast_81 <= resize(product29, 31);
--  adder_add_cast_82 <= resize(adder_add_cast_81, 32);
--  adder_add_temp_26 <= adder_add_cast_80 + adder_add_cast_82;
--  
--  sum28 <= "0111111111111111111111111111111" WHEN (adder_add_temp_26(31) = '0') AND (adder_add_temp_26(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_26(31) = '1') AND (adder_add_temp_26(30) /= '1') ELSE
--      adder_add_temp_26(30 DOWNTO 0);
--
--  delay_pipeline_28 <= delay_pipeline_1(28);
--
--  Discrete_FIR_Filter_coeff_29 <= signed(Discrete_FIR_Filter_coeff(29));
--
--  multiplier_mul_temp_29 <= delay_pipeline_28 * Discrete_FIR_Filter_coeff_29;
--  
--  product30 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_29(27) = '0') AND (multiplier_mul_temp_29(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_29(27) = '1') AND (multiplier_mul_temp_29(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_29(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_83 <= resize(sum28, 32);
--  adder_add_cast_84 <= resize(product30, 31);
--  adder_add_cast_85 <= resize(adder_add_cast_84, 32);
--  adder_add_temp_27 <= adder_add_cast_83 + adder_add_cast_85;
--  
--  sum29 <= "0111111111111111111111111111111" WHEN (adder_add_temp_27(31) = '0') AND (adder_add_temp_27(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_27(31) = '1') AND (adder_add_temp_27(30) /= '1') ELSE
--      adder_add_temp_27(30 DOWNTO 0);
--
--  delay_pipeline_29 <= delay_pipeline_1(29);
--
--  Discrete_FIR_Filter_coeff_30 <= signed(Discrete_FIR_Filter_coeff(30));
--
--  multiplier_mul_temp_30 <= delay_pipeline_29 * Discrete_FIR_Filter_coeff_30;
--  
--  product31 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_30(27) = '0') AND (multiplier_mul_temp_30(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_30(27) = '1') AND (multiplier_mul_temp_30(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_30(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_86 <= resize(sum29, 32);
--  adder_add_cast_87 <= resize(product31, 31);
--  adder_add_cast_88 <= resize(adder_add_cast_87, 32);
--  adder_add_temp_28 <= adder_add_cast_86 + adder_add_cast_88;
--  
--  sum30 <= "0111111111111111111111111111111" WHEN (adder_add_temp_28(31) = '0') AND (adder_add_temp_28(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_28(31) = '1') AND (adder_add_temp_28(30) /= '1') ELSE
--      adder_add_temp_28(30 DOWNTO 0);
--
--  delay_pipeline_30 <= delay_pipeline_1(30);
--
--  Discrete_FIR_Filter_coeff_31 <= signed(Discrete_FIR_Filter_coeff(31));
--
--  multiplier_mul_temp_31 <= delay_pipeline_30 * Discrete_FIR_Filter_coeff_31;
--  
--  product32 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_31(27) = '0') AND (multiplier_mul_temp_31(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_31(27) = '1') AND (multiplier_mul_temp_31(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_31(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_89 <= resize(sum30, 32);
--  adder_add_cast_90 <= resize(product32, 31);
--  adder_add_cast_91 <= resize(adder_add_cast_90, 32);
--  adder_add_temp_29 <= adder_add_cast_89 + adder_add_cast_91;
--  
--  sum31 <= "0111111111111111111111111111111" WHEN (adder_add_temp_29(31) = '0') AND (adder_add_temp_29(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_29(31) = '1') AND (adder_add_temp_29(30) /= '1') ELSE
--      adder_add_temp_29(30 DOWNTO 0);
--
--  delay_pipeline_31 <= delay_pipeline_1(31);
--
--  Discrete_FIR_Filter_coeff_32 <= signed(Discrete_FIR_Filter_coeff(32));
--
--  multiplier_mul_temp_32 <= delay_pipeline_31 * Discrete_FIR_Filter_coeff_32;
--  
--  product33 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_32(27) = '0') AND (multiplier_mul_temp_32(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_32(27) = '1') AND (multiplier_mul_temp_32(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_32(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_92 <= resize(sum31, 32);
--  adder_add_cast_93 <= resize(product33, 31);
--  adder_add_cast_94 <= resize(adder_add_cast_93, 32);
--  adder_add_temp_30 <= adder_add_cast_92 + adder_add_cast_94;
--  
--  sum32 <= "0111111111111111111111111111111" WHEN (adder_add_temp_30(31) = '0') AND (adder_add_temp_30(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_30(31) = '1') AND (adder_add_temp_30(30) /= '1') ELSE
--      adder_add_temp_30(30 DOWNTO 0);
--
--  delay_pipeline_32 <= delay_pipeline_1(32);
--
--  Discrete_FIR_Filter_coeff_33 <= signed(Discrete_FIR_Filter_coeff(33));
--
--  multiplier_mul_temp_33 <= delay_pipeline_32 * Discrete_FIR_Filter_coeff_33;
--  
--  product34 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_33(27) = '0') AND (multiplier_mul_temp_33(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_33(27) = '1') AND (multiplier_mul_temp_33(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_33(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_95 <= resize(sum32, 32);
--  adder_add_cast_96 <= resize(product34, 31);
--  adder_add_cast_97 <= resize(adder_add_cast_96, 32);
--  adder_add_temp_31 <= adder_add_cast_95 + adder_add_cast_97;
--  
--  sum33 <= "0111111111111111111111111111111" WHEN (adder_add_temp_31(31) = '0') AND (adder_add_temp_31(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_31(31) = '1') AND (adder_add_temp_31(30) /= '1') ELSE
--      adder_add_temp_31(30 DOWNTO 0);
--
--  delay_pipeline_33 <= delay_pipeline_1(33);
--
--  Discrete_FIR_Filter_coeff_34 <= signed(Discrete_FIR_Filter_coeff(34));
--
--  multiplier_mul_temp_34 <= delay_pipeline_33 * Discrete_FIR_Filter_coeff_34;
--  
--  product35 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_34(27) = '0') AND (multiplier_mul_temp_34(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_34(27) = '1') AND (multiplier_mul_temp_34(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_34(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_98 <= resize(sum33, 32);
--  adder_add_cast_99 <= resize(product35, 31);
--  adder_add_cast_100 <= resize(adder_add_cast_99, 32);
--  adder_add_temp_32 <= adder_add_cast_98 + adder_add_cast_100;
--  
--  sum34 <= "0111111111111111111111111111111" WHEN (adder_add_temp_32(31) = '0') AND (adder_add_temp_32(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_32(31) = '1') AND (adder_add_temp_32(30) /= '1') ELSE
--      adder_add_temp_32(30 DOWNTO 0);
--
--  delay_pipeline_34 <= delay_pipeline_1(34);
--
--  Discrete_FIR_Filter_coeff_35 <= signed(Discrete_FIR_Filter_coeff(35));
--
--  multiplier_mul_temp_35 <= delay_pipeline_34 * Discrete_FIR_Filter_coeff_35;
--  
--  product36 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_35(27) = '0') AND (multiplier_mul_temp_35(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_35(27) = '1') AND (multiplier_mul_temp_35(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_35(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_101 <= resize(sum34, 32);
--  adder_add_cast_102 <= resize(product36, 31);
--  adder_add_cast_103 <= resize(adder_add_cast_102, 32);
--  adder_add_temp_33 <= adder_add_cast_101 + adder_add_cast_103;
--  
--  sum35 <= "0111111111111111111111111111111" WHEN (adder_add_temp_33(31) = '0') AND (adder_add_temp_33(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_33(31) = '1') AND (adder_add_temp_33(30) /= '1') ELSE
--      adder_add_temp_33(30 DOWNTO 0);
--
--  delay_pipeline_35 <= delay_pipeline_1(35);
--
--  Discrete_FIR_Filter_coeff_36 <= signed(Discrete_FIR_Filter_coeff(36));
--
--  multiplier_mul_temp_36 <= delay_pipeline_35 * Discrete_FIR_Filter_coeff_36;
--  
--  product37 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_36(27) = '0') AND (multiplier_mul_temp_36(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_36(27) = '1') AND (multiplier_mul_temp_36(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_36(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_104 <= resize(sum35, 32);
--  adder_add_cast_105 <= resize(product37, 31);
--  adder_add_cast_106 <= resize(adder_add_cast_105, 32);
--  adder_add_temp_34 <= adder_add_cast_104 + adder_add_cast_106;
--  
--  sum36 <= "0111111111111111111111111111111" WHEN (adder_add_temp_34(31) = '0') AND (adder_add_temp_34(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_34(31) = '1') AND (adder_add_temp_34(30) /= '1') ELSE
--      adder_add_temp_34(30 DOWNTO 0);
--
--  delay_pipeline_36 <= delay_pipeline_1(36);
--
--  Discrete_FIR_Filter_coeff_37 <= signed(Discrete_FIR_Filter_coeff(37));
--
--  multiplier_mul_temp_37 <= delay_pipeline_36 * Discrete_FIR_Filter_coeff_37;
--  
--  product38 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_37(27) = '0') AND (multiplier_mul_temp_37(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_37(27) = '1') AND (multiplier_mul_temp_37(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_37(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_107 <= resize(sum36, 32);
--  adder_add_cast_108 <= resize(product38, 31);
--  adder_add_cast_109 <= resize(adder_add_cast_108, 32);
--  adder_add_temp_35 <= adder_add_cast_107 + adder_add_cast_109;
--  
--  sum37 <= "0111111111111111111111111111111" WHEN (adder_add_temp_35(31) = '0') AND (adder_add_temp_35(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_35(31) = '1') AND (adder_add_temp_35(30) /= '1') ELSE
--      adder_add_temp_35(30 DOWNTO 0);
--
--  delay_pipeline_37 <= delay_pipeline_1(37);
--
--  Discrete_FIR_Filter_coeff_38 <= signed(Discrete_FIR_Filter_coeff(38));
--
--  multiplier_mul_temp_38 <= delay_pipeline_37 * Discrete_FIR_Filter_coeff_38;
--  
--  product39 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_38(27) = '0') AND (multiplier_mul_temp_38(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_38(27) = '1') AND (multiplier_mul_temp_38(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_38(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_110 <= resize(sum37, 32);
--  adder_add_cast_111 <= resize(product39, 31);
--  adder_add_cast_112 <= resize(adder_add_cast_111, 32);
--  adder_add_temp_36 <= adder_add_cast_110 + adder_add_cast_112;
--  
--  sum38 <= "0111111111111111111111111111111" WHEN (adder_add_temp_36(31) = '0') AND (adder_add_temp_36(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_36(31) = '1') AND (adder_add_temp_36(30) /= '1') ELSE
--      adder_add_temp_36(30 DOWNTO 0);
--
--  delay_pipeline_38 <= delay_pipeline_1(38);
--
--  Discrete_FIR_Filter_coeff_39 <= signed(Discrete_FIR_Filter_coeff(39));
--
--  multiplier_mul_temp_39 <= delay_pipeline_38 * Discrete_FIR_Filter_coeff_39;
--  
--  product40 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_39(27) = '0') AND (multiplier_mul_temp_39(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_39(27) = '1') AND (multiplier_mul_temp_39(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_39(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_113 <= resize(sum38, 32);
--  adder_add_cast_114 <= resize(product40, 31);
--  adder_add_cast_115 <= resize(adder_add_cast_114, 32);
--  adder_add_temp_37 <= adder_add_cast_113 + adder_add_cast_115;
--  
--  sum39 <= "0111111111111111111111111111111" WHEN (adder_add_temp_37(31) = '0') AND (adder_add_temp_37(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_37(31) = '1') AND (adder_add_temp_37(30) /= '1') ELSE
--      adder_add_temp_37(30 DOWNTO 0);
--
--  delay_pipeline_39 <= delay_pipeline_1(39);
--
--  Discrete_FIR_Filter_coeff_40 <= signed(Discrete_FIR_Filter_coeff(40));
--
--  multiplier_mul_temp_40 <= delay_pipeline_39 * Discrete_FIR_Filter_coeff_40;
--  
--  product41 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_40(27) = '0') AND (multiplier_mul_temp_40(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_40(27) = '1') AND (multiplier_mul_temp_40(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_40(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_116 <= resize(sum39, 32);
--  adder_add_cast_117 <= resize(product41, 31);
--  adder_add_cast_118 <= resize(adder_add_cast_117, 32);
--  adder_add_temp_38 <= adder_add_cast_116 + adder_add_cast_118;
--  
--  sum40 <= "0111111111111111111111111111111" WHEN (adder_add_temp_38(31) = '0') AND (adder_add_temp_38(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_38(31) = '1') AND (adder_add_temp_38(30) /= '1') ELSE
--      adder_add_temp_38(30 DOWNTO 0);
--
--  delay_pipeline_40 <= delay_pipeline_1(40);
--
--  Discrete_FIR_Filter_coeff_41 <= signed(Discrete_FIR_Filter_coeff(41));
--
--  multiplier_mul_temp_41 <= delay_pipeline_40 * Discrete_FIR_Filter_coeff_41;
--  
--  product42 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_41(27) = '0') AND (multiplier_mul_temp_41(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_41(27) = '1') AND (multiplier_mul_temp_41(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_41(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_119 <= resize(sum40, 32);
--  adder_add_cast_120 <= resize(product42, 31);
--  adder_add_cast_121 <= resize(adder_add_cast_120, 32);
--  adder_add_temp_39 <= adder_add_cast_119 + adder_add_cast_121;
--  
--  sum41 <= "0111111111111111111111111111111" WHEN (adder_add_temp_39(31) = '0') AND (adder_add_temp_39(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_39(31) = '1') AND (adder_add_temp_39(30) /= '1') ELSE
--      adder_add_temp_39(30 DOWNTO 0);
--
--  delay_pipeline_41 <= delay_pipeline_1(41);
--
--  Discrete_FIR_Filter_coeff_42 <= signed(Discrete_FIR_Filter_coeff(42));
--
--  multiplier_mul_temp_42 <= delay_pipeline_41 * Discrete_FIR_Filter_coeff_42;
--  
--  product43 <= "01111111111111111111111111111" WHEN (multiplier_mul_temp_42(27) = '0') AND (multiplier_mul_temp_42(26 DOWNTO 25) /= "00") ELSE
--      "10000000000000000000000000000" WHEN (multiplier_mul_temp_42(27) = '1') AND (multiplier_mul_temp_42(26 DOWNTO 25) /= "11") ELSE
--      multiplier_mul_temp_42(25 DOWNTO 0) & '0' & '0' & '0';
--
--  adder_add_cast_122 <= resize(sum41, 32);
--  adder_add_cast_123 <= resize(product43, 31);
--  adder_add_cast_124 <= resize(adder_add_cast_123, 32);
--  adder_add_temp_40 <= adder_add_cast_122 + adder_add_cast_124;
--  
--  sum42 <= "0111111111111111111111111111111" WHEN (adder_add_temp_40(31) = '0') AND (adder_add_temp_40(30) /= '0') ELSE
--      "1000000000000000000000000000000" WHEN (adder_add_temp_40(31) = '1') AND (adder_add_temp_40(30) /= '1') ELSE
--      adder_add_temp_40(30 DOWNTO 0);

  output_typeconvert <= sum6(30 DOWNTO 16);

  Discrete_FIR_Filter_out <= std_logic_vector(output_typeconvert);

END rtl;

